/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MixinExternal {
    }
    interface MixinLocal {
        "mixinLocalText"?: string;
    }
    interface StencilPlayground {
    }
}
declare global {
    interface HTMLMixinExternalElement extends Components.MixinExternal, HTMLStencilElement {
    }
    var HTMLMixinExternalElement: {
        prototype: HTMLMixinExternalElement;
        new (): HTMLMixinExternalElement;
    };
    interface HTMLMixinLocalElement extends Components.MixinLocal, HTMLStencilElement {
    }
    var HTMLMixinLocalElement: {
        prototype: HTMLMixinLocalElement;
        new (): HTMLMixinLocalElement;
    };
    interface HTMLStencilPlaygroundElement extends Components.StencilPlayground, HTMLStencilElement {
    }
    var HTMLStencilPlaygroundElement: {
        prototype: HTMLStencilPlaygroundElement;
        new (): HTMLStencilPlaygroundElement;
    };
    interface HTMLElementTagNameMap {
        "mixin-external": HTMLMixinExternalElement;
        "mixin-local": HTMLMixinLocalElement;
        "stencil-playground": HTMLStencilPlaygroundElement;
    }
}
declare namespace LocalJSX {
    interface MixinExternal {
    }
    interface MixinLocal {
        "mixinLocalText"?: string;
    }
    interface StencilPlayground {
    }

    interface MixinLocalAttributes {
        "mixinLocalText": string;
    }

    interface IntrinsicElements {
        "mixin-external": MixinExternal;
        "mixin-local": Omit<MixinLocal, keyof MixinLocalAttributes> & { [K in keyof MixinLocal & keyof MixinLocalAttributes]?: MixinLocal[K] } & { [K in keyof MixinLocal & keyof MixinLocalAttributes as `attr:${K}`]?: MixinLocalAttributes[K] } & { [K in keyof MixinLocal & keyof MixinLocalAttributes as `prop:${K}`]?: MixinLocal[K] };
        "stencil-playground": StencilPlayground;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mixin-external": LocalJSX.IntrinsicElements["mixin-external"] & JSXBase.HTMLAttributes<HTMLMixinExternalElement>;
            "mixin-local": LocalJSX.IntrinsicElements["mixin-local"] & JSXBase.HTMLAttributes<HTMLMixinLocalElement>;
            "stencil-playground": LocalJSX.IntrinsicElements["stencil-playground"] & JSXBase.HTMLAttributes<HTMLStencilPlaygroundElement>;
        }
    }
}
