/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BaseCkeditor {
        /**
          * @default {}
         */
        "config": any;
    }
    interface ExampleWithMixin {
        "mixinText"?: string;
        /**
          * @default 'Default Text'
         */
        "text": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilCore {
    }
}
export interface BaseCkeditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBaseCkeditorElement;
}
declare global {
    interface HTMLBaseCkeditorElementEventMap {
        "editor": any;
    }
    interface HTMLBaseCkeditorElement extends Components.BaseCkeditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBaseCkeditorElementEventMap>(type: K, listener: (this: HTMLBaseCkeditorElement, ev: BaseCkeditorCustomEvent<HTMLBaseCkeditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBaseCkeditorElementEventMap>(type: K, listener: (this: HTMLBaseCkeditorElement, ev: BaseCkeditorCustomEvent<HTMLBaseCkeditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBaseCkeditorElement: {
        prototype: HTMLBaseCkeditorElement;
        new (): HTMLBaseCkeditorElement;
    };
    interface HTMLExampleWithMixinElement extends Components.ExampleWithMixin, HTMLStencilElement {
    }
    var HTMLExampleWithMixinElement: {
        prototype: HTMLExampleWithMixinElement;
        new (): HTMLExampleWithMixinElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilCoreElement extends Components.StencilCore, HTMLStencilElement {
    }
    var HTMLStencilCoreElement: {
        prototype: HTMLStencilCoreElement;
        new (): HTMLStencilCoreElement;
    };
    interface HTMLElementTagNameMap {
        "base-ckeditor": HTMLBaseCkeditorElement;
        "example-with-mixin": HTMLExampleWithMixinElement;
        "my-component": HTMLMyComponentElement;
        "stencil-core": HTMLStencilCoreElement;
    }
}
declare namespace LocalJSX {
    interface BaseCkeditor {
        /**
          * @default {}
         */
        "config"?: any;
        "onEditor"?: (event: BaseCkeditorCustomEvent<any>) => void;
    }
    interface ExampleWithMixin {
        "mixinText"?: string;
        /**
          * @default 'Default Text'
         */
        "text"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilCore {
    }

    interface BaseCkeditorAttributes {
        "config": string;
    }
    interface ExampleWithMixinAttributes {
        "mixinText": string;
        "text": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "base-ckeditor": Omit<BaseCkeditor, keyof BaseCkeditorAttributes> & { [K in keyof BaseCkeditor & keyof BaseCkeditorAttributes]?: BaseCkeditor[K] } & { [K in keyof BaseCkeditor & keyof BaseCkeditorAttributes as `attr:${K}`]?: BaseCkeditorAttributes[K] } & { [K in keyof BaseCkeditor & keyof BaseCkeditorAttributes as `prop:${K}`]?: BaseCkeditor[K] };
        "example-with-mixin": Omit<ExampleWithMixin, keyof ExampleWithMixinAttributes> & { [K in keyof ExampleWithMixin & keyof ExampleWithMixinAttributes]?: ExampleWithMixin[K] } & { [K in keyof ExampleWithMixin & keyof ExampleWithMixinAttributes as `attr:${K}`]?: ExampleWithMixinAttributes[K] } & { [K in keyof ExampleWithMixin & keyof ExampleWithMixinAttributes as `prop:${K}`]?: ExampleWithMixin[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "stencil-core": StencilCore;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "base-ckeditor": LocalJSX.IntrinsicElements["base-ckeditor"] & JSXBase.HTMLAttributes<HTMLBaseCkeditorElement>;
            "example-with-mixin": LocalJSX.IntrinsicElements["example-with-mixin"] & JSXBase.HTMLAttributes<HTMLExampleWithMixinElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-core": LocalJSX.IntrinsicElements["stencil-core"] & JSXBase.HTMLAttributes<HTMLStencilCoreElement>;
        }
    }
}
